-- LOG_GROUPS --
CREATE TABLE IF NOT EXISTS LA_LOG_GROUPS(
  LOG_GROUP_ID BIGINT AUTO_INCREMENT,
  NAME VARCHAR(100),
  TENANT_ID INT,
  USER_NAME VARCHAR(255),
  PRIMARY KEY(LOG_GROUP_ID,NAME)
);

-- LOG_STREAMS --
CREATE TABLE IF NOT EXISTS LA_LOG_STREAMS(
  STREAM_ID BIGINT AUTO_INCREMENT,
  LOG_GROUP_ID BIGINT,
  NAME VARCHAR(255),
  PRIMARY KEY(STREAM_ID),
  FOREIGN KEY(LOG_GROUP_ID) REFERENCES LA_LOG_GROUPS(LOG_GROUP_ID)
);

-- LOG_STREAMS --
CREATE TABLE IF NOT EXISTS LA_LOG_STREAM_METADATA(
  ID BIGINT AUTO_INCREMENT,
  STREAM_ID VARCHAR(255) DEFAULT NOT NULL ,
  FIELDS VARCHAR(255),
  TENANT_ID INT,
  USER_NAME VARCHAR(255),
  PRIMARY KEY (STREAM_ID,TENANT_ID,USER_NAME)
);
